<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>top</string>
	</array>
	<key>name</key>
	<string>qichat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>proposal, user rules, concepts</string>
			<key>match</key>
			<string>(proposal|u\d*|concept|dynamic):</string>
			<key>name</key>
			<string>storage.source.qichat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords</string>
			<key>match</key>
			<string>(include|language|topic):</string>
			<key>name</key>
			<string>keyword.source.qichat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.source.qichat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.construct</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.source.qichat</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>operators with parameters</string>
			<key>match</key>
			<string>(\^(?:play|(?:run|start|wait|stop)(?:Tag){0,1}|clear|(?:de){0,1}activate|notExist|exist|goto(?:Reactivate){0,1}|topicTag|mode))\(([\w/-]*)\)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators without parameters</string>
			<key>match</key>
			<string>\^(first|rand|repeat|private|stayInScope|mode|noPick|(next|previous|same)Proposal)</string>
			<key>name</key>
			<string>support.function.construct</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>topic tags</string>
			<key>match</key>
			<string>%[\w-]*</string>
			<key>name</key>
			<string>entity.name.tag.source.qichat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ALMemory variable</string>
			<key>match</key>
			<string>\$[\w/-]*</string>
			<key>name</key>
			<string>constant.other.source.qichat</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.source.qichat</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.source.qichat</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>ALMemory event</string>
			<key>match</key>
			<string>(e:)([\w/-]*)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>TTS tags</string>
			<key>match</key>
			<string>\\((PAU|RSPD|VCT|RMW|SPD|VOL)=\d+|RST)\\</string>
			<key>name</key>
			<string>constant.language.source.qichat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>concept references</string>
			<key>match</key>
			<string>~\w*</string>
			<key>name</key>
			<string>variable.language.source.qichat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Matemathical and logical operators</string>
			<key>match</key>
			<string>[=&lt;&gt;]+</string>
			<key>name</key>
			<string>string.other.math.tex.source.qichat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.qichat</string>
	<key>uuid</key>
	<string>afd8e4d5-0a8a-4a65-9b40-f16e6ab77861</string>
</dict>
</plist>
